<?php

use Triposhub\Ubunifu\Application\Model;
use Triposhub\Ubunifu\Application\View;

class Uview extends View
{
    const view_dir = 'view';
    public $file;
    public $use_template;
    public $link;


    function __construct()
    {
        parent::__construct();
         $this ->link = $this ->linkto().$this ->app();
    }

    function render($filename, $model = [], $scripts = [])
    {
        $this->file = $filename;
        if ($model) {
            foreach ($model as $key => $value) {
                $this->{$key} = $value;
            }
        }

        if ($scripts) {
            foreach ($scripts as $key => $value) {
                $this->{$key} = $value;
            }
        }

        if ($this->use_template) {
            require AppConfig::load('public_dir', 'app') .self::view_dir . '/_theme.php';
        } else {
            if (isset($this->file)) {
                require AppConfig::load('app_dir', 'app') .strtoupper(Model::App()->urlTabs()->getApp()). '/' . self::view_dir . '/' . $this->file . '.php';
            }
        }
    }

    function useTemplate($option = true)
    {
        $this->use_template = $option;
    }

    function url()
    {
        return parent::url(); // TODO: Change the autogenerated stub
    }

    function content($file)
    {
        if (isset($file)) {
            require AppConfig::load('app_dir', 'app') . strtoupper(Model::App()->urlTabs()->getApp()) . '/' . self::view_dir . '/' . $file . '.php';
        }
    }

    function layout($file)
    {
        if (isset($file)) {
            require AppConfig::load('public_dir', 'app')  . self::view_dir . '/' . $file . '.php';
        }
    }

    function account($page = true,$model = [])
    {
        if ($model) {
            foreach ($model as $key => $value) {
                $this->{$key} = $value;
            }
        }
        $page = strtoupper($page);
        if($page === 'LOGIN'){
            require AppConfig::load('public_dir', 'app') . self::view_dir . '/account/login.php';
        }
        if($page === 'FORGOT'){
            require AppConfig::load('public_dir', 'app') . self::view_dir . '/account/forgot-password.php';
        }
        if($page === 'VERIFY'){
            require AppConfig::load('public_dir', 'app') . self::view_dir . '/account/login.php';

        }
    }

    function linkto()
    {
        return Model::App()->base_url();
    }

    function app()
    {
        return Model::App()->urlTabs()->getApp();
    }

}